# Default initial positions for my_dual_robot_cell's ros2_control fake system

initial_positions:
  alice_elbow_joint: 0
  alice_shoulder_lift_joint: 0
  alice_shoulder_pan_joint: 0
  alice_wrist_1_joint: 0
  alice_wrist_2_joint: 0
  alice_wrist_3_joint: 0
  bob_elbow_joint: 0
  bob_shoulder_lift_joint: 0
  bob_shoulder_pan_joint: 0
  bob_wrist_1_joint: 0
  bob_wrist_2_joint: 0
  bob_wrist_3_joint: 0