name: Humble Binary Testing
on:
  workflow_dispatch:
  pull_request:
    branches:
      - humble
  push:
    branches:
      - humble

jobs:
  humble_binary_testing:
    uses: ./.github/workflows/reusable_ici.yml
    with:
      ros_distro: humble
      ros_repo: testing
      ref_for_scheduled_build: humble
