name: Rolling Binary Main
on:
  workflow_dispatch:
    branches:
      - main
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '34 12 * * 0'

jobs:
  rolling_binary_main:
    uses: ./.github/workflows/reusable_ici.yml
    with:
      ros_distro: rolling
      ros_repo: main
      ref_for_scheduled_build: main
      rosdep_skip_keys: >-
        moveit_ros_move_group
        moveit_kinematics
        moveit_planners
        moveit_simple_controller_manager
        moveit_configs_utils
        moveit_ros_visualization
        moveit_setup_assistant
